### ISSUE TITLE
link from the documentation is not working. Typp

### ISSUE THREAD

**Issue by anikiej** [feanor-anglin/GetWired-Software#4]
->Tis<- is software for GetWired Home Automation Modules by Domatic, open home automation hardware previously released at >>>openhardware.io<<< (page not working).

**Comment by feanor-anglin** [comment]
This is an openhardware.io related issue. All profiles on openhardware are currently inaccessible. I will ask them for support. Thank you for reporting.

**Comment by feanor-anglin** [comment]
Page is online again.
